---
- hosts: k8s
  remote_user: root

  vars:
    test: wxdlong
    version: v1.17.4

  tasks: 
    - name: say hello
      shell: |
          swapoff -a && sysctl -w vm.swappiness=0
          > /etc/sysctl.d/98-ok8s.conf
          echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.d/98-ok8s.conf
          echo "net.bridge.bridge-nf-call-iptables = 1" >> /etc/sysctl.d/98-ok8s.conf
          echo "net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.d/98-ok8s.conf
          echo "net.bridge.bridge-nf-call-arptables = 1" >> /etc/sysctl.d/98-ok8s.conf
          echo "net.ipv6.conf.all.forwarding = 1" >> /etc/sysctl.d/98-ok8s.conf
          echo "net.ipv6.conf.default.forwarding = 1" >> /etc/sysctl.d/98-ok8s.conf
          sysctl -p /etc/sysctl.d/98-ok8s.conf

          iptables -F && iptables -X \
              && iptables -F -t nat && iptables -X -t nat \
              && iptables -F -t raw && iptables -X -t raw \
              && iptables -F -t mangle && iptables -X -t mangle
          systemctl disable firewalld


    - name: rename image
      shell: | 
          docker tag k8s.gcr.io/kube-proxy-amd64:{{ version }} k8s.gcr.io/kube-proxy:{{ version }}
          docker tag k8s.gcr.io/kube-apiserver-amd64:{{ version }} k8s.gcr.io/kube-apiserver:{{ version }}
          docker tag k8s.gcr.io/kube-controller-manager-amd64:{{ version }} k8s.gcr.io/kube-controller-manager:{{ version }}
          docker tag k8s.gcr.io/kube-scheduler-amd64:{{ version }} k8s.gcr.io/kube-scheduler:{{ version }}
